language: objective-c
osx_image: xcode8
script: xcodebuild -workspace TestGreenhouse.xcworkspace -scheme Release
#xcode_workspace: TestGreenhouse.xcworkspace
#xcode_scheme: Release
#xcode_sdk: iphonesimulator
# safelist
branches:
  only:
  - Swift-3.0
