language: objective-c
osx_image: xcode8
script: 
  - xcodebuild -workspace TestGreenhouse.xcworkspace -scheme Release ONLY_ACTIVE_ARCH=NO
before_script:
  - chmod a+x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
# safelist
branches:
  only:
  - Swift-3.0
#This sends a slack notificatio to just me, you can configure easily
notifications:
  slack: pathfindersoftware:rsq2vyDTwHR6wg54iVIpuH2u

